services:
  - type: web
    name: mentormatchpro
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mentormatchpro-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health

databases:
  - name: mentormatchpro-db
    databaseName: mentormatchpro
    plan: free
